import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";

import Logo from "@/assets/images/logo.svg";
import MenuIcon from "@/assets/images/icon-menu.svg";
import IllustrationWorking from "@/assets/images/illustration-working.svg";

import FacebookLogo from "@/assets/images/icon-facebook.svg";
import TwitterLogo from "@/assets/images/icon-twitter.svg";
import PinterestLogo from "@/assets/images/icon-pinterest.svg";
import InstagramLogo from "@/assets/images/icon-instagram.svg";

import { advancedStatisticsData, footerNavLinksData } from "@/dataList/data";

import {
  AdvancedStatistics,
  BoostContainer,
  Container,
  Divider,
  Footer,
  Header,
  Main,
  MainFirstContent,
  Hamburger,
  NavigationMenu,
  ShortenLinkForm,
  SocialList,
} from "@/styles/pages/Home";
import Button from "@/components/Button";
import AdvancedStatisticsList from "@/components/AdvancedStatisticsList";
import FooterMenuList from "@/components/FooterMenuList";
import { SubmitHandler, useForm } from "react-hook-form";
import Link from "next/link";

interface InputProps {
  link: string;
}

const Home: NextPage = () => {
  const [isNavExpanded, setIsNavExpanded] = useState(false);
  const [windowSize, setWindowSize] = useState(0);
  const {
    register,
    handleSubmit,
    getValues,
    formState: { errors },
  } = useForm<InputProps>();
  const onSubmit: SubmitHandler<InputProps> = (data) => console.log(data);

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.addEventListener("resize", () => setWindowSize(window.innerWidth));
    }
  }, []);

  return (
    <Container>
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Logo fontSize={135} height={35} fill="#34313D" />

        <Hamburger onClick={() => setIsNavExpanded(!isNavExpanded)}>
          <MenuIcon fontSize={35} />
        </Hamburger>

        <NavigationMenu isHidden={isNavExpanded || windowSize > 860}>
          <ul>
            <li>
              <Link href="/">
                <a>Features</a>
              </Link>
            </li>
            <li>
              <Link href="/">
                <a>Pricing</a>
              </Link>
            </li>
            <li>
              <Link href="/">
                <a>Resources</a>
              </Link>
            </li>
          </ul>
          <Divider />
          <ul>
            <li>
              <button>Login</button>
            </li>
            <li>
              <button className="button-with-cyan-background">Sign Up</button>
            </li>
          </ul>
        </NavigationMenu>
      </Header>
      <Main>
        <MainFirstContent>
          <IllustrationWorking
            className="illustration-working"
            fontSize={340}
            width="100%"
            viewBox="0 0 520 482"
          />
          <div>
            <h1>More than just shorter links</h1>
            <p>
              Build your brand&apos;s recognition and get detailed insights on
              how your links are performing.
            </p>
            <Button>Get Started</Button>
          </div>
        </MainFirstContent>
        <AdvancedStatistics>
          <ShortenLinkForm onSubmit={handleSubmit(onSubmit)}>
            <div>
              <input
                className={
                  errors.link && getValues.length > 0
                    ? "input input-with-error"
                    : "input"
                }
                type="text"
                placeholder="Shorter a link here..."
                {...register("link", { required: true })}
              />
              {errors.link && <p>Please add a link</p>}
            </div>
            <button type="submit">Shorten It!</button>
          </ShortenLinkForm>

          <h1>Advanced Statistics</h1>
          <p>
            Track how your links are performing across the web with our advanced
            statistics dashboard.
          </p>
          <div className="advanced-statistics-list-container">
            <AdvancedStatisticsList data={advancedStatisticsData} />
          </div>
        </AdvancedStatistics>
        <BoostContainer>
          <h1>Boost your links today</h1>
          <Button>Get Started</Button>
        </BoostContainer>
      </Main>
      <Footer>
        <div className="footer-container">
          <Logo fontSize={100} height={35} style={{ color: "#fff" }} />
          <div>
            <FooterMenuList data={footerNavLinksData} />
            <SocialList>
              <li>
                <Link href="/">
                  <a>
                    <FacebookLogo fontSize={24} />
                  </a>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <a>
                    <TwitterLogo fontSize={24} />
                  </a>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <a>
                    <PinterestLogo fontSize={24} />
                  </a>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <a>
                    <InstagramLogo fontSize={24} />
                  </a>
                </Link>
              </li>
            </SocialList>
          </div>
        </div>
      </Footer>
    </Container>
  );
};

export default Home;
