import type { NextPage } from "next";
import { FunctionComponent, SVGProps, useEffect, useState } from "react";
import Head from "next/head";

import Logo from "@/assets/images/logo.svg";
import MenuIcon from "@/assets/images/icon-menu.svg";
import IllustrationWorking from "@/assets/images/illustration-working.svg";
import BrandRecognition from "@/assets/images/icon-brand-recognition.svg";
import DetailedRecords from "@/assets/images/icon-detailed-records.svg";
import FullyCustomizable from "@/assets/images/icon-fully-customizable.svg";
import FacebookLogo from "@/assets/images/icon-facebook.svg";
import TwitterLogo from "@/assets/images/icon-twitter.svg";
import PinterestLogo from "@/assets/images/icon-pinterest.svg";
import InstagramLogo from "@/assets/images/icon-instagram.svg";

import {
  AdvancedStatistics,
  BoostContainer,
  Container,
  Divider,
  Footer,
  Header,
  Main,
  MainFirstContent,
  Hamburger,
  NavigationMenu,
  ShortenLinkForm,
  SocialList,
} from "@/styles/pages/Home";
import Button from "@/components/Button";
import AdvancedStatisticsList from "@/components/AdvancedStatisticsList";
import FooterMenuList from "@/components/FooterMenuList";
import { SubmitHandler, useForm } from "react-hook-form";

interface InputProps {
  link: string;
}

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    getValues,
    formState: { errors },
  } = useForm<InputProps>();
  const onSubmit: SubmitHandler<InputProps> = (data) => console.log(data);
  const [isNavExpanded, setIsNavExpanded] = useState(false);
  const [windowSize, setWindowSize] = useState(0);

  const advancedStatisticsData: {
    Icon: FunctionComponent<SVGProps<SVGSVGElement>>;
    title: string;
    text: string;
  }[] = [
    {
      Icon: BrandRecognition,
      title: "Brand Recognition",
      text: "Boost your brand recognition with each click. Generic links don&apos;t mean a thing. Branded links help instil confidence in your content",
    },
    {
      Icon: DetailedRecords,
      title: "Detailed Records",
      text: "Gain insights into who is clicking your links. Knowing when and where people engage with your content helps inform better decisions.",
    },
    {
      Icon: FullyCustomizable,
      title: "Fully Customizable",
      text: "Improve brand awareness and content discoverability through customizable links, supercharging audience engagement.",
    },
  ];

  const footerNavLinksData = [
    {
      title: "Features",
      items: [
        { item: "Link Shortening", link: "https://www.google.com/" },
        { item: "Branded Links", link: "https://www.google.com/" },
        { item: "Analytics", link: "https://www.google.com/" },
      ],
    },
    {
      title: "Resources",
      items: [
        { item: "Blog", link: "https://www.google.com" },
        { item: "Developers", link: "https://www.google.com" },
        { item: "Support", link: "https://www.google.com" },
      ],
    },
    {
      title: "Company",
      items: [
        { item: "About", link: "https://www.google.com" },
        { item: "Our Team", link: "https://www.google.com" },
        { item: "Careers", link: "https://www.google.com" },
        { item: "Contact", link: "https://www.google.com" },
      ],
    },
  ];

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.addEventListener("resize", () => setWindowSize(window.innerWidth));
    }
  }, []);

  return (
    <Container>
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Logo fontSize={135} height={35} fill="#34313D" />

        <Hamburger onClick={() => setIsNavExpanded(!isNavExpanded)}>
          <MenuIcon fontSize={35} />
        </Hamburger>

        <NavigationMenu isHidden={isNavExpanded || windowSize > 860}>
          <ul>
            <li>Features</li>
            <li>Pricing</li>
            <li>Resources</li>
          </ul>
          <Divider />
          <ul>
            <li>
              <button>Login</button>
            </li>
            <li>
              <button className="button-with-cyan-background">Sign Up</button>
            </li>
          </ul>
        </NavigationMenu>
      </Header>
      <Main>
        <MainFirstContent>
          <IllustrationWorking
            className="illustration-working"
            fontSize={340}
            width="100%"
            viewBox="0 0 520 482"
          />
          <h1>More than just shorter links</h1>
          <p>
            Build your brand&apos;s recognition and get detailed insights on how
            your links are performing.
          </p>
          <Button>Get Started</Button>
        </MainFirstContent>
        <ShortenLinkForm onSubmit={handleSubmit(onSubmit)}>
          <input
            className={
              errors.link && getValues.length > 0
                ? "input input-with-error"
                : "input"
            }
            type="text"
            placeholder="Shorter a link here..."
            {...register("link", { required: true })}
          />
          {errors.link && <p>Please add a link</p>}
          <button type="submit">Shorten It!</button>
        </ShortenLinkForm>
        <AdvancedStatistics>
          <h1>Advanced Statistics</h1>
          <p>
            Track how your links are performing across the web with our advanced
            statistics dashboard.
          </p>
          <AdvancedStatisticsList data={advancedStatisticsData} />
        </AdvancedStatistics>
        <BoostContainer>
          <h1>Boost your links today</h1>
          <Button>Get Started</Button>
        </BoostContainer>
      </Main>
      <Footer>
        <Logo fontSize={100} height={35} style={{ color: "#fff" }} />
        <FooterMenuList data={footerNavLinksData} />
        <SocialList>
          <li>
            <FacebookLogo fontSize={24} />
          </li>
          <li>
            <TwitterLogo fontSize={24} />
          </li>
          <li>
            <PinterestLogo fontSize={24} />
          </li>
          <li>
            <InstagramLogo fontSize={24} />
          </li>
        </SocialList>
      </Footer>
    </Container>
  );
};

export default Home;
